name: Python Test Workflow
on: workflow_dispatch
jobs:
  Python-Test-job:
   runs-on: ubuntu-latest
   steps:
     - name: checkout-code
       uses: actions/checkout@v3
     - name: Setup Python Version
       uses: actions/setup-python@v3
       with:
          python-version: 3.9 # Install the python version needed

     - name: Install Python dependencies
       run: |
           python -m pip install --upgrade pip requests # Install the dependencies (if needed)
           pip install -r requirements.txt
     - name: Execute Python script # Run the script.py file to get the latest data
       run: python Python/py_flask.py
