name: Python Test Workflow
on: workflow_dispatch
jobs:
  Python-Test-job:
   runs-on: ubuntu-latest
   steps:
     - name: checkout-code
       uses: actions/checkout@v3
     # - name: Run Python 
     #   run:  python test.py
     - name: Setup Python Version
       uses: actions/setup-python@v2
       with:
          python-version: 3.8 # Install the python version needed

     - name: Install Python dependencies
       run: python -m pip install --upgrade pip requests # Install the dependencies (if needed)

     - name: Execute Python script # Run the script.py file to get the latest data
       run: python test.py
